# Generated by Django 4.0.6 on 2022-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('device_address', models.CharField(max_length=200)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
